name: LuhnDotNet - Benchmark.Net
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Benchmark.Net for LuhnDotNet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 8.0.404

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 9.0.100

      - name: Run benchmark project
        run: dotnet run --exporters JSON --filter '*' --project benchmark/LuhnDotNetBenchmark.csproj --property:Configuration=Release --runtimes net8.0 net9.0 -f net9.0

      - name: Store helper benchmark results
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Analyze helper benchmark results
          tool: 'benchmarkdotnet'
          gh-pages-branch: helper-benchmark-results
          benchmark-data-dir-path: ./
          output-file-path: BenchmarkDotNet.Artifacts/results/LuhnDotNetBenchmark.HelperBenchmark-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@shinji-san'

      - name: Store Luhn benchmark results
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Analyze Luhn benchmark results
          tool: 'benchmarkdotnet'
          gh-pages-branch: luhn-benchmark-results
          benchmark-data-dir-path: ./
          output-file-path: BenchmarkDotNet.Artifacts/results/LuhnDotNetBenchmark.LuhnBenchmark-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@shinji-san'

      - name: Store Mod11AscendingWeights benchmark results
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Analyze Mod11AscendingWeights benchmark results
          tool: 'benchmarkdotnet'
          gh-pages-branch: mod11asc-benchmark-results
          benchmark-data-dir-path: ./
          output-file-path: BenchmarkDotNet.Artifacts/results/LuhnDotNetBenchmark.Mod11AscendingWeightBenchmark-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@shinji-san'
          
      - name: Store Damm benchmark results
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Analyze Damm benchmark results
          tool: 'benchmarkdotnet'
          gh-pages-branch: damm-benchmark-results
          benchmark-data-dir-path: ./
          output-file-path: BenchmarkDotNet.Artifacts/results/LuhnDotNetBenchmark.DammBenchmark-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@shinji-san'