name: LuhnDotNet - Documentation

on:
  workflow_run:
    workflows:
      - LuhnDotNet - Benchmark.Net
    types:
      - completed
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy documentation"
        required: true
        default: "staging"

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 8.0.404

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 9.0.100

      - name: Update docfx
        run: dotnet tool update -g docfx

      - name: Run docfx
        run: docfx docfx.json

      - name: Checkout Helper Benchmark Results in subdirectory
        uses: actions/checkout@v4
        with:
          ref: helper-benchmark-results
          path: helper-benchmark-results

      - name: Checkout Luhn Benchmark Results in subdirectory
        uses: actions/checkout@v4
        with:
          ref: luhn-benchmark-results
          path: luhn-benchmark-results

      - name: Checkout Damm Benchmark Results in subdirectory
        uses: actions/checkout@v4
        with:
          ref: damm-benchmark-results
          path: damm-benchmark-results

      - name: Checkout Mod11 Asc Benchmark Results in subdirectory
        uses: actions/checkout@v4
        with:
          ref: mod11asc-benchmark-results
          path: mod11asc-benchmark-results

      - name: Copy benchmark results to _site
        run: |
          rsync -av --exclude '.git' helper-benchmark-results/ _site/helper-benchmark-results/
          rsync -av --exclude '.git' luhn-benchmark-results/ _site/luhn-benchmark-results/
          rsync -av --exclude '.git' damm-benchmark-results/ _site/damm-benchmark-results/
          rsync -av --exclude '.git' mod11asc-benchmark-results/ _site/mod11asc-benchmark-results/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4