name: LuhnDotNet - Build and Test All .NET Versions

on:
  push:
    branches:
    - '*'
    tags-ignore:
    - '*'
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4.3.0
      with:
        dotnet-version: 8.0.404

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4.3.0
      with:
        dotnet-version: 9.0.100

    - name: Restore
      run: dotnet restore LuhnDotNet.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore LuhnDotNet.sln

    - name: Test
      run: dotnet test --no-restore --no-build --configuration Release LuhnDotNet.sln

    - name: Prepare README.md for NuGet package
      run: |
        grep -n "## Install LuhnDotNet package" README.md | cut -d: -f 1| xargs -i tail -n +{} README.md > TMP.md && sed -i '1s/^/# Setup\r\n/' TMP.md && mv -f TMP.md README.md
        grep -n "# CLI building instructions" README.md | cut -d: -f 1| xargs -i head -n {} README.md | head -n -1 > TMP.md && mv -f TMP.md README.md

    - name: Create Package
      run: dotnet pack --no-restore --no-build --configuration Release LuhnDotNet.sln
