name: LuhnDotNet (All supported TFM)

on:
  push:
    branches:
    - '*'
    tags-ignore:
    - '*'
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.416

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.403

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.100

    - name: .NET Core SxS
      run: |
        rsync -a ${DOTNET_ROOT/8.0.100/7.0.403/6.0.416}/* $DOTNET_ROOT/

    - name: Restore
      run: dotnet restore LuhnDotNet.sln

    - name: Build
      run: dotnet build --configuration Release LuhnDotNet.sln

    - name: Test
      run: dotnet test --configuration Release LuhnDotNet.sln

    - name: Prepare README.md for NuGet package
      run: |
        grep -n "## Install LuhnDotNet package" README.md | cut -d: -f 1| xargs -i tail -n +{} README.md > TMP.md && sed -i '1s/^/# Setup\r\n/' TMP.md && mv -f TMP.md README.md
        grep -n "# CLI building instructions" README.md | cut -d: -f 1| xargs -i head -n {} README.md | head -n -1 > TMP.md && mv -f TMP.md README.md

    - name: Create Package
      run: dotnet pack --configuration Release LuhnDotNet.sln
